export type LaptopT = {
  id: number;
  title: string;
  price: number;
  brand: string;
  model: string;
  shortDesc: string;
  gpuBrand: string;
  gpuModel: string;
  graphicsType: "Integrated" | "Dedicated";
  vram: string;
  backlightType: string;
  processorBrand: "Intel" | "AMD" | "Apple";
  processorModel: string;
  cores: number;
  threads: number;
  ram: string;
  ramType: "DDR3" | "DDR4" | "DDR5";
  storageType: "HDD" | "SSD" | "HDD + SSD";
  storageCapacity: string;
  screenSize: string;
  screenResolution: string;
  refreshRate: string;
  weight?: string;
  year: number;
  description: string;
  images: string[];
  tag?: string[];
  stockStatus: "reserved" | "sold" | "in stock";
  status: "approved" | "pending" | "rejected" | "archived";
  userId: number;
  condition: "new" | "used" | "refurbished";
};
